config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :vehicles, path: 'home', only: [:index]
  get '/', to: redirect('/home')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  after_create :update_city_and_state!, if: :update_city_and_state?

  validates :color, presence: true
  validates :size, presence: true
  validates :price, presence: true
  validates :mileage, presence: true

  def self.colors
    ["Orange", "Yellow", "Green", "Red", "Gold", "Gray", "Blue", "Silver", "Maroon", "White", "Brown", "Black", "Tan", "Other"]
  end

  def self.sizes
    ["Convertible", "Crossover Utility Vehicle", "Sedan", "Pickup", "Minivan", "Wagon", "Coupe", "Van", "Wagon / Hatchback", "Suv"]
  end

  protected

  def update_city_and_state?
    city.present? && state.nil?
  end

  private

  def update_city_and_state!
    self.state = city.partition('- ').last
    self.city = city.slice(0..(city.index('-'))-1)
    self.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/errors.rb
module Errors
  extend ActiveSupport::Concern

  included do
    before_action :find_errors?
  end

  def find_errors?
    @errors = {}

    if params[:min_price].present? && params[:max_price].present?
      @errors[:price] = 'Min Price can not be higher than Max Price' unless params[:min_price] <= params[:max_price]
    end

    if params[:min_mileage].present? && params[:max_mileage].present?
      @errors[:mileage] = 'Min Mileage can not be higher than Max Mileage' unless params[:min_mileage] <= params[:max_mileage]
    end
    puts 'Errors:'
    puts @errors
    @errors
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  include Errors

  def index
    if @errors.empty?
      result = Vehicles::Search.call(search_params: search_params)

      @total_count = result.total_count
      @vehicles = Kaminari.paginate_array(result.vehicles).page(params[:page])
    end
  end

  private

  def search_params
    search_filters = {}
    search_filters[:color] = params[:color] if params[:color].present?
    search_filters[:size] = params[:size] if params[:size].present?
    search_filters[:min_mileage] = params[:min_mileage] if params[:min_mileage].present?
    search_filters[:max_mileage] = params[:max_mileage] if params[:max_mileage].present?
    search_filters[:min_price] = params[:min_price] if params[:min_price].present?
    search_filters[:max_price] = params[:max_price] if params[:max_price].present?
    search_filters
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carshop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vehicles/_errors.html.erb
<p><strong>Errors:</strong>
<% if @errors[:price].present? %>
  <p><%= @errors[:price] %></p>
<% end %>
<% if @errors[:mileage].present? %>
  <p><%= @errors[:mileage] %></p>
<% end %>

app/views/vehicles/_filters.html.erb
<h3>Filtered by: </h3>
<ul>
  <% if params[:color].present? %>
    <li>Color: <%= params[:color]%></li>
  <% end %>
  <% if params[:size].present? %>
    <li>Color: <%= params[:size]%></li>
  <% end %>
  <% if params[:min_mileage].present? %>
    <li>Mileage (Min): <%= params[:min_mileage]%></li>
  <% end %>
  <% if params[:max_mileage].present? %>
    <li>Mileage (Max): <%= params[:max_mileage]%></li>
  <% end %>
  <% if params[:min_price].present? %>
    <li>Price (Min): <%= params[:min_price]%></li>
  <% end %>
  <% if params[:max_price].present? %>
    <li>Price (Max): <%= params[:max_price]%></li>
  <% end %>
</ul>

app/views/vehicles/_form.html.erb
<%= form_with url: vehicles_path, local: true, method: :get do |f| %>
  <div class="form_group">
    <%= f.label 'Filter by Color:' %>
    <%= f.select(:color, options_for_select(Vehicle.colors.map { |color| color }.sort), include_blank: 'Select color', class: "form_input") %>
  </div>
  <div class="form_group">
    <%= f.label 'Filter by Size:' %>
    <%= f.select(:size , options_for_select(Vehicle.sizes.map { |size| size }), include_blank: 'Select size', class: "form_input") %>
  </div>
  <div class="form_group">
    <%= f.label 'Mileage (Min):' %>
    <%= f.number_field(:min_mileage, min: 1000, max: 100000, step: 1000) %>
  </div>
  <div class="form_group">
    <%= f.label 'Mileage (Max):' %>
    <%= f.number_field(:max_mileage, min: 1000, max: 100000, step: 1000) %>
  </div>
  <div class="form_group">
    <%= f.label 'Price (Min):' %>
    <%= f.number_field(:min_price, min: 1000, max: 100000, step: 1000) %>
  </div>
  <div class="form_group">
    <%= f.label 'Price (Max):' %>
    <%= f.number_field(:max_price, min: 1000, max: 100000, step: 1000) %>
  </div>
  <div class="form_group">
    <%= f.submit "Search", class: "btn btn_primary" %>
  </div>
<% end %>

app/views/vehicles/_result.html.erb
<h2>Results:</h2>

<% if @vehicles.present? %>
  <p><%= @total_count %> result(s)</p>
  <%= paginate @vehicles %>
  <table>
    <thead>
      <tr>
        <th>Year</th>
        <th>Make</th>
        <th>Model</th>
        <th>Model Series</th>
        <th>Color</th>
        <th>Size (Type)</th>
        <th>Price</th>
        <th>Mileage</th>
        <th>City</th>
        <th>State</th>
      </tr>
    </thead>

    <tbody id="vehicles">
      <%= render partial: 'vehicles/vehicle', collection: @vehicles %>
    </tbody>
  </table>
  <%= paginate @vehicles %>
<% else %>
  <p> Nothing to show </p>
<% end %>

app/views/vehicles/_vehicle.html.erb
<tr>
  <th><%= vehicle.year %></th>
  <th><%= vehicle.make.humanize %></th>
  <th><%= vehicle.model.humanize %></th>
  <th><%= vehicle.model_series %></th>
  <th><%= vehicle.color %></th>
  <th><%= vehicle.size %></th>
  <th><%= vehicle.price %></th>
  <th><%= vehicle.mileage %></th>
  <th><%= vehicle.city %></th>
  <th><%= vehicle.state %></th>
</tr>

app/views/vehicles/index.html.erb
<h2>Carshop Application</h2>

<% if @errors.any? %>
  <%= render partial: 'vehicles/errors' %>
<% end %>

<%= render partial: 'vehicles/form' %>

<%= render partial: 'vehicles/filters' %>

<%= render partial: 'vehicles/result' %>